### PR TITLE
Update packages to RTM

### PR DESCRIPTION
**Pull request by andrewlock**
Updated the package.json and global.json to 1.0.0 versions
All tests pass so I don't think there should be anything else required.

### CODE REVIEW

**Comment by khellang** [comment]
Thanks for this @Andrew lock! :heart:

The reason I haven't gotten around to updating for RTM is that I'm on vacation. I'll get this merged and a new version pushed some time next week :smile:

**Comment by andrewlock** [comment]
No problem, I saw you mention on the spec tests thread you were on vacation so thought I'd save you the trouble:) 

Luckily the move to RTM didn't seem to break any of the tests so was a pretty simple change. Enjoy the rest of your holiday!

**Comment by khellang** [comment]
Thanks again! I'll get a new version out ASAP. Just need to install the new tooling for VS (takes ages :stuck_out_tongue:)

**Comment by andrewlock** [comment]
No problem, just happy to be contributing!:smile:

**Pull request merged**
